name: internship_todos_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.7
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  package_info_plus: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter_native_splash:
  color: "#0A1E2D"
  android: true
  ios: true
  image: "assets/images/logo.png"

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FF0A1E2D"
  adaptive_icon_foreground: "assets/images/logo-adaptive.png"
  ios: false
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
